name: ci

on: [push, pull_request]

permissions:
  contents: read

jobs:
  Linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Update apt cache
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y libbsd-dev libssl-dev
      - name: Build
        run: make
        env:
          CC: ${{ matrix.cc }}
          CFLAGS: -Werror -DUSE_COPY_FILE_RANGE
      - name: Install
        run: make install
        env:
          PREFIX: /tmp/usr/local
